# Generated by Django 5.2.4 on 2025-08-17 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Check', '0002_department_employee_delete_profile_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dep_name',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=40)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Check.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DEPARTMENT_NAME', to='Check.department')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Check.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Cources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=40)),
                ('student', models.ManyToManyField(to='Check.student')),
                ('teacher', models.ManyToManyField(to='Check.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
