# Generated by Django 5.2.4 on 2025-08-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Check', '0003_rename_dep_name_department_name_teacher_student_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cources',
            table='Cources',
        ),
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='Teacher',
        ),
    ]
