# Generated by Django 5.2.4 on 2025-08-22 08:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Check', '0004_alter_cources_table_alter_department_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='cources',
            name='student',
            field=models.ManyToManyField(blank=True, to='Check.student'),
        ),
        migrations.AlterField(
            model_name='cources',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='Check.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Check.department'),
        ),
    ]
